/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ControllerHome;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JTable;
/**
 *
 * @author HYPE AMD
 */
public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    private ControllerHome cbt;
    public FormHome() {
        initComponents();
        cbt = new ControllerHome(this);
        cbt.isiTableTeam();
        cbt.isiTablePlayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
    
    public JTextField getTxtCariNamaTeam() {
        return txtCariNamaTeam;
    }
   
    
    public JButton getButtonCariNamaTeam() {
        return buttonCariNamaTeam;
    }
    
 
    
    public JTable getTabelDataTeam() {
        return tabelDataTeam;
    }
    
    public JTextField getTxtCariIGN() {
        return txtCariIGN;
    }
    
 
    
    public JButton getButtonCariIGN() {
        return buttonCariIGN;
    }
    
  
    
    public JTable getTabelDataPlayer() {
        return tabelDataPlayer;
    }
    
    public JButton getButtonKelolaTeam() {
        return buttonKelolaTeam;
    }
    
    public JButton getButtonKelolaPlayer() {
        return buttonKelolaPlayer;
    }
    
    public JButton getButtonRefreshTeam() {
        return buttonRefreshTeam;
    }
    
    public JButton getButtonRefreshPlayer() {
        return buttonRefreshPlayer;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariNamaTeam = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDataTeam = new javax.swing.JTable();
        buttonCariNamaTeam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCariIGN = new javax.swing.JTextField();
        buttonCariIGN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelDataPlayer = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        buttonKelolaTeam = new javax.swing.JButton();
        buttonKelolaPlayer = new javax.swing.JButton();
        buttonRefreshTeam = new javax.swing.JButton();
        buttonRefreshPlayer = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEM DATA ESPORTS");

        jLabel2.setText("Cari Nama Team");

        txtCariNamaTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariNamaTeamActionPerformed(evt);
            }
        });

        tabelDataTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelDataTeam);

        buttonCariNamaTeam.setText("CARI NAMA TEAM");
        buttonCariNamaTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariNamaTeamActionPerformed(evt);
            }
        });

        jLabel4.setText("Cari Nama Player (In Game Name)");

        buttonCariIGN.setText("CARI IGN");
        buttonCariIGN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariIGNActionPerformed(evt);
            }
        });

        tabelDataPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelDataPlayer);

        jLabel6.setText("Kelola Data");

        buttonKelolaTeam.setText("DATA TEAM");
        buttonKelolaTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelolaTeamActionPerformed(evt);
            }
        });

        buttonKelolaPlayer.setText("DATA PLAYER");
        buttonKelolaPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelolaPlayerActionPerformed(evt);
            }
        });

        buttonRefreshTeam.setText("REFRESH");
        buttonRefreshTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshTeamActionPerformed(evt);
            }
        });

        buttonRefreshPlayer.setText("REFRESH");
        buttonRefreshPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshPlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRefreshTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCariNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(txtCariIGN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRefreshPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCariIGN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonKelolaTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonKelolaPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(499, 499, 499))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCariNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCariNamaTeam)
                    .addComponent(jLabel4)
                    .addComponent(txtCariIGN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCariIGN)
                    .addComponent(jLabel6)
                    .addComponent(buttonRefreshTeam)
                    .addComponent(buttonRefreshPlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonKelolaTeam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonKelolaPlayer)
                            .addGap(327, 327, 327))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariNamaTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariNamaTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariNamaTeamActionPerformed

    private void buttonKelolaTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelolaTeamActionPerformed
        // TODO add your handling code here:
        FormTeam ft = new FormTeam();
        ft.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKelolaTeamActionPerformed

    private void buttonKelolaPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelolaPlayerActionPerformed
        // TODO add your handling code here:
        FormPlayer fp = new FormPlayer();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKelolaPlayerActionPerformed

    private void buttonCariNamaTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariNamaTeamActionPerformed
        // TODO add your handling code here:
        cbt.cariNamaTeam();
    }//GEN-LAST:event_buttonCariNamaTeamActionPerformed

    private void buttonCariIGNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariIGNActionPerformed
        // TODO add your handling code here:
        cbt.cariIGN();
    }//GEN-LAST:event_buttonCariIGNActionPerformed

    private void buttonRefreshTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshTeamActionPerformed
        // TODO add your handling code here:
        cbt.isiTableTeam();
    }//GEN-LAST:event_buttonRefreshTeamActionPerformed

    private void buttonRefreshPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshPlayerActionPerformed
        // TODO add your handling code here:
        cbt.isiTablePlayer();
    }//GEN-LAST:event_buttonRefreshPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCariIGN;
    private javax.swing.JButton buttonCariNamaTeam;
    private javax.swing.JButton buttonKelolaPlayer;
    private javax.swing.JButton buttonKelolaTeam;
    private javax.swing.JButton buttonRefreshPlayer;
    private javax.swing.JButton buttonRefreshTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelDataPlayer;
    private javax.swing.JTable tabelDataTeam;
    private javax.swing.JTextField txtCariIGN;
    private javax.swing.JTextField txtCariNamaTeam;
    // End of variables declaration//GEN-END:variables
}
